using System.Threading.Tasks;
using Grpc.Core;
using Corestream.Tenant; // Autogenerated namespace from tenant.proto
using LuminaCast.Backend.Infrastructure;
using System.Text.Json;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace LuminaCast.Backend.Services
{
    public class TenantService : Corestream.Tenant.TenantService.TenantServiceBase
    {
        private readonly ITenantRepository _repository;
        private readonly ILogger<TenantService> _logger;
        private readonly AppDbContext _dbContext;

        public TenantService(ITenantRepository repository, ILogger<TenantService> logger, AppDbContext dbContext)
        {
            _repository = repository;
            _logger = logger;
            _dbContext = dbContext;
        }

        public override async Task<GetTenantResponse> GetTenant(GetTenantRequest request, ServerCallContext context)
        {
            // ISO 27001 Annex A.12.4: Log all access attempts
            _logger.LogInformation("Audit: Attempting to resolve tenant with ID or Domain: {DomainOrId}. Client IP: {Peer}", 
                request.DomainOrId, context.Peer);

            var entity = await _repository.GetTenantByIdOrDomainAsync(request.DomainOrId);

            if (entity == null)
            {
                _logger.LogWarning("Audit: Tenant not found for {DomainOrId}. Attempting fallback.", request.DomainOrId);
                // Fallback to wealthloom per requirements if not found
                entity = await _repository.GetTenantByIdOrDomainAsync("wealthloom");
                
                if (entity == null)
                {
                    _logger.LogError("Audit: Critical failure - Fallback tenant also not found.");
                    throw new RpcException(new Status(StatusCode.NotFound, "Tenant not found and fallback failed."));
                }
            }

            _logger.LogInformation("Audit: Successfully resolved tenant {TenantId} for request {DomainOrId}", entity.Id, request.DomainOrId);

            var response = new GetTenantResponse
            {
                Tenant = new TenantConfig
                {
                    Id = entity.Id,
                    Name = entity.Name,
                    Company = entity.Company,
                    Description = entity.Description,
                    CustomDomain = entity.CustomDomain ?? "",
                    LogoUrl = entity.LogoUrl ?? "",
                    Brand = new Brand
                    {
                        First = entity.Brand.First,
                        Second = entity.Brand.Second,
                        PrimaryColor = entity.Brand.PrimaryColor,
                        SecondaryColor = entity.Brand.SecondaryColor
                    }
                }
            };

            foreach (var p in entity.PricingTiers)
            {
                var pt = new PricingTier
                {
                    Name = p.Name,
                    Price = p.Price
                };
                
                var features = JsonSerializer.Deserialize<string[]>(p.FeaturesJson);
                if (features != null)
                {
                    pt.Features.AddRange(features);
                }
                
                response.Tenant.Pricing.Add(pt);
            }

            return response;
        }

        [Microsoft.AspNetCore.Authorization.Authorize]
        public override Task<GetSecureDashboardResponse> GetSecureDashboard(GetSecureDashboardRequest request, ServerCallContext context)
        {
            var userId = context.GetHttpContext().User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value ?? "Unknown User";

            _logger.LogInformation("Audit: Authorized access to secure dashboard by User: {UserId} for Tenant: {TenantId}", userId, request.TenantId);

            return Task.FromResult(new GetSecureDashboardResponse
            {
                SecretMessage = $"Welcome to the secure vault, User {userId}. This data is cryptographically protected by ISO 27001 Access Controls."
            });
        }

        [Microsoft.AspNetCore.Authorization.Authorize]
        public override async Task<VideoResponse> GetSecureVideoUrl(VideoRequest request, ServerCallContext context)
        {
            var userId = context.GetHttpContext().User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
            if (string.IsNullOrEmpty(userId))
            {
                throw new RpcException(new Status(StatusCode.Unauthenticated, "Invalid JWT Token"));
            }

            var student = await _dbContext.Students
                .Include(s => s.Subscriptions)
                .ThenInclude(sub => sub.PricingTier)
                .FirstOrDefaultAsync(s => s.Id == userId);

            if (student == null || !student.Subscriptions.Any(s => s.Status == "active"))
            {
                _logger.LogWarning("Audit: User {UserId} attempted to access video {VideoId} without an active subscription.", userId, request.VideoId);
                throw new RpcException(new Status(StatusCode.PermissionDenied, "Active subscription required."));
            }

            var video = await _dbContext.Videos
                .Include(v => v.CourseVideos)
                .FirstOrDefaultAsync(v => v.Id == request.VideoId);

            if (video == null)
            {
                throw new RpcException(new Status(StatusCode.NotFound, "Video not found."));
            }

            // Check if the student has a subscription to a PricingTier that links to a Course containing this video
            var activeCourseIds = student.Subscriptions
                .Where(s => s.Status == "active" && s.PricingTier.CourseId.HasValue)
                .Select(s => s.PricingTier.CourseId.Value)
                .ToList();

            bool hasAccess = video.CourseVideos.Any(cv => activeCourseIds.Contains(cv.CourseId));
            
            if (!hasAccess)
            {
                _logger.LogWarning("Audit: User {UserId} does not have the required course access for video {VideoId}.", userId, request.VideoId);
                throw new RpcException(new Status(StatusCode.PermissionDenied, "Your subscription does not include the course for this video."));
            }

            _logger.LogInformation("Audit: Anti-Piracy verification passed for User {UserId} on Video {VideoId}.", userId, request.VideoId);
            
            var service = context.GetHttpContext().RequestServices.GetService(typeof(IVideoDeliveryService)) as IVideoDeliveryService;
            var url = service?.GeneratePresignedUrl(video.S3ObjectKey, 60);

            return new VideoResponse
            {
                Title = video.Title,
                PresignedUrl = url ?? ""
            };
        }

        // Admin Endpoints
        [Microsoft.AspNetCore.Authorization.Authorize]
        public override Task<GetUploadUrlResponse> GetUploadUrl(GetUploadUrlRequest request, ServerCallContext context)
        {
            // In a real app, verify the user has the "Creator" role
            var objectKey = $"uploads/{System.Guid.NewGuid()}-{request.Filename}";
            
            var service = context.GetHttpContext().RequestServices.GetService(typeof(IVideoDeliveryService)) as IVideoDeliveryService;
            var url = service?.GeneratePresignedPutUrl(objectKey, request.ContentType, 60);

            _logger.LogInformation("Audit: Generated Upload URL for new object {ObjectKey}", objectKey);

            return Task.FromResult(new GetUploadUrlResponse
            {
                UploadUrl = url ?? "",
                ObjectKey = objectKey
            });
        }

        [Microsoft.AspNetCore.Authorization.Authorize]
        public override async Task<CreateCourseResponse> CreateCourse(CreateCourseRequest request, ServerCallContext context)
        {
            // In a real app, verify the user has the "Creator" role and get their TenantId
            var tenantId = "default_tenant"; 

            var course = new Course
            {
                Title = request.Title,
                Description = request.Description,
                TenantId = tenantId
            };

            foreach (var videoId in request.VideoIds)
            {
                course.CourseVideos.Add(new CourseVideo
                {
                    VideoId = videoId,
                    OrderIndex = course.CourseVideos.Count
                });
            }

            _dbContext.Courses.Add(course);
            await _dbContext.SaveChangesAsync();

            _logger.LogInformation("Audit: Created new course {CourseId} with {VideoCount} videos.", course.Id, request.VideoIds.Count);

            return new CreateCourseResponse
            {
                CourseId = course.Id,
                Success = true
            };
        }
    }
}
